### ISSUE TITLE
config updated message from all commands

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/cli#125]
SUCCESS  Configfile updated (0s)
is printed as the first output from every command, it probably shouldn't be updated for all commands or at least not printed.

**Comment by asalkeld** [comment]
To explain: It probably happened because @davemooreuws added the javascript glob default to the config.

In general it gets printed only when you update the cli and we introduce a new default.
If it is happening *all* the time then it is a bug.. 
Yes we could remove the tasklet wrapper that creates the print out. Or maybe change the text to "updating config file defaults"
